package windows;

import Domain.Categorias;
import Domain.Producto;
import Domain.Subasta;
import Domain.Usuario;
import Metodos.TextPrompt;
import java.awt.*;
import java.io.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodos.imgTabla;

public class Home extends javax.swing.JFrame {

    TextPrompt ph;
    Usuario usuario;
    Producto producto;
    Subasta subasta;
    ArrayList<Subasta> ListaSubasta = new ArrayList<>();
    ArrayList<Usuario> ListaUsuarios = new ArrayList<>();
    ArrayList<Producto> ListaProducto = new ArrayList<>();
    ArrayList<Categorias> ListaCategorias = new ArrayList<>();
    int i;

    public Home(Usuario usuarios) {
        initComponents();
        this.usuario = usuarios;
        this.setLocationRelativeTo(null);

        tb_Productos.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tb_Productos.getTableHeader().setOpaque(false);
        tb_Productos.getTableHeader().setBackground(new Color(32, 136, 203));
        tb_Productos.getTableHeader().setForeground(new Color(255, 255, 255));
        tb_Productos.setRowHeight(160);
        tb_Productos.setDefaultRenderer(Object.class, new imgTabla());

        this.extraerdatos();
        this.extraerProductos();
        this.extraerCategorias();
        this.mostrar();
    }

    public Home() {

    }

    public void filter() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        OfertaActual = new javax.swing.JLabel();
        oferta_min = new javax.swing.JLabel();
        Lbl_OfertaMinima = new javax.swing.JLabel();
        lbl_fechaInicio = new javax.swing.JLabel();
        lbl_fechaFinal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_postor = new javax.swing.JLabel();
        lbl_ofertaActual = new javax.swing.JLabel();
        TxtOferta = new javax.swing.JTextField();
        n_pro = new javax.swing.JLabel();
        ofertarMonto = new javax.swing.JButton();
        descripcion = new javax.swing.JLabel();
        CategoriaProducto = new javax.swing.JLabel();
        fechaInicial = new javax.swing.JLabel();
        TiempoRestante = new javax.swing.JLabel();
        EstadoProducto = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_ofert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Productos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        in_user = new javax.swing.JLabel();
        cmb_categorias = new javax.swing.JComboBox<>();
        btn_reset = new javax.swing.JLabel();
        btn_fil = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(241, 241, 241));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Info. Producto"));

        OfertaActual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OfertaActual.setText("Oferta Actual: ");

        oferta_min.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        oferta_min.setText("Oferta minima :");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Postor actual :");

        n_pro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        n_pro.setForeground(new java.awt.Color(102, 102, 255));
        n_pro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ofertarMonto.setText("Ofertar");
        ofertarMonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ofertarMontoMouseClicked(evt);
            }
        });

        descripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        CategoriaProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        fechaInicial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fechaInicial.setText("Incio de subasta:");

        TiempoRestante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TiempoRestante.setText("Fecha de cierre : ");

        EstadoProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EstadoProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EstadoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_OfertaMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_fechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addComponent(lbl_fechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ofertaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(oferta_min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(198, 198, 198))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_postor, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(OfertaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fechaInicial)
                                        .addComponent(TiempoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(TxtOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(46, 46, 46)
                                            .addComponent(ofertarMonto)))))
                            .addGap(270, 270, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                .addComponent(n_pro, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                .addComponent(CategoriaProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(227, Short.MAX_VALUE)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(EstadoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lbl_fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lbl_fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Lbl_OfertaMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(lbl_ofertaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(n_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(CategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addComponent(fechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(TiempoRestante)
                    .addGap(32, 32, 32)
                    .addComponent(oferta_min)
                    .addGap(31, 31, 31)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbl_postor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addComponent(OfertaActual)
                    .addGap(42, 42, 42)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ofertarMonto))
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_ofert.setBackground(new java.awt.Color(102, 102, 255));
        btn_ofert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ofert.setForeground(new java.awt.Color(255, 255, 255));
        btn_ofert.setText("Observar Produco");
        btn_ofert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ofertMouseClicked(evt);
            }
        });

        tb_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Estado", "Categoria", "Fecha cierre", "Vendedor", "Imagen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Productos.setFocusable(false);
        tb_Productos.setGridColor(new java.awt.Color(204, 204, 204));
        tb_Productos.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tb_Productos.setShowGrid(false);
        tb_Productos.setShowHorizontalLines(true);
        tb_Productos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tb_Productos);
        if (tb_Productos.getColumnModel().getColumnCount() > 0) {
            tb_Productos.getColumnModel().getColumn(1).setPreferredWidth(20);
            tb_Productos.getColumnModel().getColumn(5).setPreferredWidth(110);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ofert, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ofert, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("OFFERED & SOLD");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vender");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito-de-compras.png"))); // NOI18N
        jLabel7.setText("Compras");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("x");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        in_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        in_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iniciar-sesion (1).png"))); // NOI18N
        in_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        in_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                in_userMouseClicked(evt);
            }
        });

        cmb_categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eliga una categoria...", " " }));
        cmb_categorias.setBorder(null);
        cmb_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_categoriasActionPerformed(evt);
            }
        });

        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_available_updates_24px_1.png"))); // NOI18N
        btn_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });

        btn_fil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_24px.png"))); // NOI18N
        btn_fil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_fil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_filMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_man_with_beard_product_box_50px.png"))); // NOI18N
        jLabel3.setText("Tus Productos");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(in_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_fil)
                .addGap(26, 26, 26)
                .addComponent(btn_reset)
                .addGap(107, 107, 107)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(in_user, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_fil, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.dispose();
        GUIProductos gp = new GUIProductos(usuario);
        gp.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.dispose();
        Compras cr = new Compras(usuario);
        cr.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void in_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in_userMouseClicked
        this.dispose();
        InfoUsuario iu = new InfoUsuario(this.usuario);
        iu.setVisible(true);
    }//GEN-LAST:event_in_userMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cmb_categorias.removeAllItems();
        cmb_categorias.addItem("Elige una categorias...");
        cargarCategorias();
    }//GEN-LAST:event_formWindowOpened

    private void btn_ofertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ofertMouseClicked
        int i = this.tb_Productos.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Debe selecionar un Producto", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            if (ListaProducto.get(i).getNombre().equals(tb_Productos.getModel().getValueAt(i, 0).toString())) {
                JOptionPane.showMessageDialog(this, "Ofrece un cantidad mayor al postor que esta actualmente para asi ser el tu el nuevo y tengas mas oportunidad de ganar", "Advertencia", JOptionPane.WARNING_MESSAGE);
                n_pro.setText(ListaProducto.get(i).getNombre());
                descripcion.setText(ListaProducto.get(i).getDescripcion());
                CategoriaProducto.setText("Categoria : " + ListaProducto.get(i).getCategoria());
                lbl_fechaInicio.setText(ListaProducto.get(i).getFechaInificio().toString());
                lbl_fechaFinal.setText(ListaProducto.get(i).getFechaFinal().toString());
                Lbl_OfertaMinima.setText(" $ " + String.valueOf(ListaProducto.get(i).getValorMininimo()));
                EstadoProducto.setText("Estado : " + ListaProducto.get(i).getEstado());
            }
        }

    }//GEN-LAST:event_btn_ofertMouseClicked

    private void cmb_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_categoriasActionPerformed

    }//GEN-LAST:event_cmb_categoriasActionPerformed

    private void btn_filMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_filMouseClicked

        String tipo = cmb_categorias.getSelectedItem().toString();

        ArrayList<Producto> filtrado = new ArrayList<>();
        for (int j = 0; j < ListaProducto.size(); j++) {
            if (ListaProducto.get(j).getCategoria().equals(tipo)) {
                filtrado.add(ListaProducto.get(j));
            }
        }
        DefaultTableModel modelo = new DefaultTableModel();

        modelo = (DefaultTableModel) tb_Productos.getModel();
        modelo.setNumRows(filtrado.size());
        for (int j = 0; j < filtrado.size(); j++) {

            modelo.setValueAt(filtrado.get(j).getNombre(), j, 0);
            modelo.setValueAt(filtrado.get(j).getEstado(), j, 1);
            modelo.setValueAt(filtrado.get(j).getCategoria(), j, 2);
            modelo.setValueAt(filtrado.get(j).getFechaFinal(), j, 3);
            JLabel jl = new JLabel();
            jl.setIcon(new ImageIcon(filtrado.get(j).getImagen()));
            modelo.setValueAt(jl, j, 5);
        }
    }//GEN-LAST:event_btn_filMouseClicked

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        this.mostrar();
    }//GEN-LAST:event_btn_resetMouseClicked

    private void ofertarMontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ofertarMontoMouseClicked
        Subasta subastas = new Subasta();
        for (int j = 0; j < ListaSubasta.size(); j++) {
            String lista = ListaSubasta.get(j).getProducto().getNombre();
            if (ListaSubasta.contains(ListaSubasta.get(j).equals(lista))) {
                subasta.setProducto(producto);
                subastas.setNombrePostor(usuario.getNombre());
                subastas.setMonto(Float.parseFloat(this.TxtOferta.getText()));

                JOptionPane.showMessageDialog(null, "Eres el nuevo mayor postor de la subasta de este producto");
                this.TxtOferta.setText("");
                this.ListaSubasta.set(j, subasta);
                this.almcenardatosSubasta();
            } else {
                subasta.setProducto(producto);
                subastas.setNombrePostor(usuario.getNombre());
                subastas.setMonto(Float.parseFloat(this.TxtOferta.getText()));

                JOptionPane.showMessageDialog(null, "Eres el nuevo mayor postor de la subasta de este producto");
                this.TxtOferta.setText("");
                this.ListaSubasta.add(subasta);
                this.almcenardatosSubasta();
            }
        }

    }//GEN-LAST:event_ofertarMontoMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        TusProductos tp = new TusProductos(usuario);
        tp.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    public void almcenardatosSubasta() {
        try {
            ObjectOutputStream salida = new ObjectOutputStream(new FileOutputStream("subasta.dat"));

            salida.writeObject(this.ListaSubasta);
            JOptionPane.showMessageDialog(null, "Se ha registrado con exito");
        } catch (IOException e) {
            System.out.println("Error al escribir en el archivo " + e.getMessage());
        }
    }

    public void almcenardatos() {
        try {
            ObjectOutputStream salida = new ObjectOutputStream(new FileOutputStream("productos.dat"));

            salida.writeObject(this.ListaProducto);
            JOptionPane.showMessageDialog(null, "Se ha registrado con exito");
        } catch (IOException e) {
            System.out.println("Error al escribir en el archivo " + e.getMessage());
        }
    }

    public void extraerProductos() {

        try {
            try ( ObjectInputStream entrada = new ObjectInputStream(new FileInputStream("productos.dat"))) {
                this.ListaProducto = (ArrayList<Producto>) entrada.readObject();
            }
        } catch (IOException | ClassNotFoundException e) {
            System.out.println("Error al escribir en el archivo " + e.getMessage());
        }
    }

    public void limpiar() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) this.tb_Productos.getModel();

        for (int k = 0; k <= modelo.getRowCount(); k++) {
            modelo.removeRow(0);
        }
    }

    public Producto buscar(String nombre) {
        Producto aux = null;
        for (int k = 0; k <= this.ListaProducto.size(); k++) {
            if (this.ListaProducto.get(k).getNombre().equals(nombre)) {
                aux = this.ListaProducto.get(k);
                i = k;
                break;
            }
        }
        return aux;
    }

    public void extraerdatosSubastas() {

        try {
            try ( ObjectInputStream entrada = new ObjectInputStream(new FileInputStream("subasta.dat"))) {
                this.ListaSubasta = (ArrayList<Subasta>) entrada.readObject();
            }
        } catch (IOException | ClassNotFoundException e) {
            System.out.println("Error al escribir en el archivo " + e.getMessage());
        }
    }

    public void mostrar() {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo = (DefaultTableModel) this.tb_Productos.getModel();
        modelo.setNumRows(this.ListaProducto.size());
        for (int j = 0; j < this.ListaProducto.size(); j++) {

            modelo.setValueAt(this.ListaProducto.get(j).getNombre(), j, 0);
            modelo.setValueAt(this.ListaProducto.get(j).getEstado(), j, 1);
            modelo.setValueAt(this.ListaProducto.get(j).getCategoria(), j, 2);
            modelo.setValueAt(this.ListaProducto.get(j).getFechaFinal(), j, 3);
            modelo.setValueAt(this.ListaProducto.get(j).getVendedor(), j, 4);
            JLabel jl = new JLabel();
            jl.setIcon(new ImageIcon(this.ListaProducto.get(j).getImagen()));
            modelo.setValueAt(jl, j, 5);
        }
    }

    public void extraerdatos() {
        try {
            ObjectInputStream entrada = new ObjectInputStream(new FileInputStream("usuarios.dat"));
            this.ListaUsuarios = (ArrayList<Usuario>) entrada.readObject();

            entrada.close();
        } catch (Exception e) {
            System.out.println("Error al escribir en el archivo " + e.getMessage());
        }
    }

    public void extraerCategorias() {
        try {
            ObjectInputStream entrada = new ObjectInputStream(new FileInputStream("categorias.dat"));
            this.ListaCategorias = (ArrayList<Categorias>) entrada.readObject();

            entrada.close();
        } catch (Exception e) {
            System.out.println("Error al escribir en el archivo " + e.getMessage());
        }
    }

    public void cargarCategorias() {

        if (ListaCategorias == null || ListaCategorias.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe agregar las Categorias");
            return;
        }
        cmb_categorias.removeAllItems();
        cmb_categorias.addItem("Categorias...");
        for (Categorias c : ListaCategorias) {
            cmb_categorias.addItem(c.getNombre());
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoriaProducto;
    private javax.swing.JLabel EstadoProducto;
    private javax.swing.JLabel Lbl_OfertaMinima;
    private javax.swing.JLabel OfertaActual;
    private javax.swing.JLabel TiempoRestante;
    private javax.swing.JTextField TxtOferta;
    private javax.swing.JLabel btn_fil;
    private javax.swing.JButton btn_ofert;
    private javax.swing.JLabel btn_reset;
    private javax.swing.JComboBox<String> cmb_categorias;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel fechaInicial;
    private javax.swing.JLabel in_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_fechaFinal;
    private javax.swing.JLabel lbl_fechaInicio;
    private javax.swing.JLabel lbl_ofertaActual;
    private javax.swing.JLabel lbl_postor;
    private javax.swing.JLabel n_pro;
    private javax.swing.JLabel oferta_min;
    private javax.swing.JButton ofertarMonto;
    private javax.swing.JTable tb_Productos;
    // End of variables declaration//GEN-END:variables
}
